# List the names of all character pairs such that each is a foe of the other. 
PREFIX foaf: <http://xmlns.com/foaf/0.1/#>
PREFIX dbpedia: <http://es.dbpedia.org/ontology/>

SELECT DISTINCT ?characterOneName ?characterTwoName
WHERE
{
	?characterOne <http://www.w3.org/TR/rdf-schema/#type> dbpedia:FictionalCharacter ;
	foaf:name ?characterOneName;
	<https://raw.github.com/nlr/masws/master/vocab.n3#foe> ?characterTwo.

	?characterOneFoe <http://www.w3.org/TR/rdf-schema/#type> dbpedia:FictionalCharacter ;
	foaf:name ?characterTwoName.

	?characterTwo <https://raw.github.com/nlr/masws/master/vocab.n3#foe> ?characterOne.
	?characterOne <https://raw.github.com/nlr/masws/master/vocab.n3#foe> ?characterTwo.
}
